[build]
  functions = "api"

[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200

[[schedule]]
function = "warmUp"
cron = "*/15 * * * *"

[functions.submitItem]
  timeout = 30  # timeout set to 30 seconds